### ISSUE TITLE
per-endpoint user consent is incompatible with Distributed Hash Table usecase

### ISSUE THREAD

**Issue by thejh** [WICG/direct-sockets#15]
https://github.com/WICG/raw-sockets/blob/master/docs/explainer.md lists "Distributed Hash Tables for P2P systems" as a usecase, but the "security considerations" section seems to suggest that user consent would be required for each host. This combination seems infeasible.

**Comment by GrapeGreen** [comment]
This issue is old, but it feels wrong to me to close it without reiterating that 
- As of now we don't have any prospects on turning this into an Open Web API 😒 
- Consent dialogue is no longer a thing for Isolated Web Apps.
