### ISSUE TITLE
Align with WebSocketStream on opening

### ISSUE THREAD

**Issue by domenic** [WICG/direct-sockets#18]
WebSocketStream (shipped in Chromium) is an example of a duplex stream of the type used here for TCP sockets. However, the design differs from yours in how the stream is created and opened. It would probably be worth aligning.

See [WebSocketStream API design](https://docs.google.com/document/d/1La1ehXw76HP6n1uUeks-WJGFgAnpX2tCjKts7QFJ57Y/edit#) and the [explainer](https://github.com/ricea/websocketstream-explainer/blob/master/README.md). I can't actually find the spec... @ricea?

**Comment by domenic** [comment]
Bump on this issue; alignment seems fairly important here.

**Comment by domenic** [comment]
Note that WebSocketStream is not shipped anywhere and so there is room for give and take on the design as well. The higher-level priority is that the two be roughly aligned. Right now this API uses `await navigator.openX(options)` and `WebSocketStream` uses `await (new WebSocketStream(url, options)).connection`, which is unnecessarily misaligned.

In general [we prefer classes to be constructible](https://w3ctag.github.io/design-principles/#constructors) so the `WebSocketStream` design is more idiomatic. It also avoids the awkward nesting under `navigator`.

Another interesting divergence is that `close()` returns a promise in your design but does not in WebSocketStream. I think your design might be better in this regard.

**Comment by ricea** [comment]
I like the idea of returning a promise from `close()`. I've filed an issue to keep track of it: https://github.com/ricea/websocketstream-explainer/issues/13.

**Comment by yume-chan** [comment]
WebTransport API has a more detailed spec text: https://www.w3.org/TR/webtransport/#web-transport

It also uses constructors to create new sockets.

**Comment by reillyeon** [comment]
We've made this change, though settled on naming the attribute `opened` instead of `connection` so that it makes sense for UDP sockets, which are connectionless. I propose closing this issue.

**Comment by GrapeGreen** [comment]
I'll close this for now following Reilly's comment above.
