### ISSUE TITLE
Create a ReadableByteStream for TCP sockets

### ISSUE THREAD

**Issue by reillyeon** [WICG/direct-sockets#49]
TCP is a byte stream transport so it should create a `ReadableByteStream` rather than a regular byte stream. This will also allow developers to create a "byob" stream reader and avoid allocating memory for receive buffers.

**Comment by reillyeon** [comment]
Example PR adding this to the Web Serial API: https://github.com/WICG/serial/pull/137

**Comment by GrapeGreen** [comment]
https://github.com/WICG/direct-sockets/pull/65
