### ISSUE TITLE
keepAliveDelay setting: milliseconds vs boolean

### ISSUE THREAD

**Issue by vapier** [WICG/direct-sockets#54]
the TCP constructor defines keepAliveDelay as so:
> https://wicg.github.io/direct-sockets/#tcpsocketoptions-dictionary
> keepAliveDelay member
> Enables TCP Keep-Alive by setting SO_KEEPALIVE option on the socket equal to the specified Keep-Alive ping delay in milliseconds.

i don't understand this as SO_KEEPALIVE is a boolean in the UNIX & Windows worlds, it isn't a ping delay in milliseconds.
* [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_10_16) -- "Non-zero requests periodic transmission of keepalive messages (protocol-specific)."
* [Windows](https://docs.microsoft.com/en-us/windows/win32/winsock/so-keepalive) -- "This value is treated as a boolean value with 0 used to indicate FALSE (disabled) and a nonzero value to indicate TRUE (enabled)."

so what system/API is this targeting, and how are implementers expected to support it ?

**Comment by vapier** [comment]
hmm, i see Chrome at least is using `TCP_KEEPIDLE` & `TCP_KEEPINTVL` on UNIX systems while treating `SO_KEEPALIVE` as a proper boolean.  so the docs are just misleading here.

**Comment by GrapeGreen** [comment]
Fixed in https://github.com/WICG/direct-sockets/pull/63
