### ISSUE TITLE
Define high trust mode

### ISSUE THREAD

**Issue by johnwilander** [WICG/direct-sockets#61]
Hi! The proposal says “The api will only be available in high-trust mode.”

Is this high trust mode specified/described somewhere? If so, can you link it, please? If not, can you describe it here?

**Comment by GrapeGreen** [comment]
Hi! Please take a look at the explainer for [Isolated Web Apps](https://github.com/WICG/isolated-web-apps/blob/main/README.md)  — that’s the current plan for Direct Sockets.
